import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Layers3 } from "lucide-react";
import { ArchitectureDiagram } from "@/components/content-cards";
import { ProjectMockup } from "@/components/portfolio-grid";
import { Badge, ButtonLink, CheckList, Container, Eyebrow, Section, SectionHeading } from "@/components/ui";
import { caseStudies, getBySlug } from "@/lib/content";
import { pageMetadata } from "@/lib/site";

export function generateStaticParams() { return caseStudies.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const study = getBySlug(caseStudies, (await params).slug); return study ? pageMetadata(study.title, study.description, `/work/${study.slug}`) : {}; }

export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) {
  const study = getBySlug(caseStudies, (await params).slug); if (!study) notFound();
  return <>
    <section className="border-b border-zinc-200 bg-zinc-950 py-14 text-white sm:py-20"><Container><Link href="/work" className="text-sm text-zinc-400 hover:text-white">Work <span aria-hidden="true">/</span></Link><div className="mt-8 grid gap-9 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><Badge tone="dark">{study.type}</Badge><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">{study.title}</h1><p className="mt-5 max-w-lg text-lg leading-8 text-zinc-300">{study.description}</p><div className="mt-7 flex flex-wrap gap-2">{study.technologies.map((technology) => <span key={technology} className="rounded-full border border-white/15 px-3 py-1 text-xs text-zinc-300">{technology}</span>)}</div></div><ProjectMockup title={study.title} modules={study.modules.slice(0, 4)} accent={study.accent} /></div></Container></section>
    <Section><Container><div className="grid gap-12 lg:grid-cols-2"><div><Eyebrow>The problem</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight text-zinc-950">Complex service, fragmented experience.</h2><p className="mt-5 text-base leading-7 text-zinc-600">{study.problem}</p></div><div className="rounded-lg border border-zinc-200 bg-zinc-50 p-7 sm:p-9"><Eyebrow>The solution</Eyebrow><p className="mt-4 text-xl font-semibold leading-8 tracking-tight text-zinc-950">{study.solution}</p></div></div></Container></Section>
    <Section className="border-y border-zinc-200 bg-zinc-50"><Container><SectionHeading eyebrow="Key features" title="Built around the work people need to do." /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{study.modules.map((module, index) => <div className="flex items-center gap-3 rounded-md border border-zinc-200 bg-white p-4" key={module}><span className="text-xs font-semibold text-blue-600">{String(index + 1).padStart(2, "0")}</span><span className="text-sm font-medium text-zinc-800">{module}</span></div>)}</div></Container></Section>
    <Section><Container><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><SectionHeading eyebrow="Architecture" title="A modular foundation for change." description="This concept is framed as a secure, modular product: clear domain boundaries, a reliable system of record, and interfaces that evolve without losing the operational thread." /><div className="mt-8"><ArchitectureDiagram items={study.architecture} /></div></div><div className="rounded-lg border border-zinc-200 p-7"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-blue-50 text-blue-700"><Layers3 className="size-5" /></span><h3 className="text-lg font-semibold text-zinc-950">User roles</h3></div><CheckList items={study.roles} className="mt-6" /></div></div></Container></Section>
    <Section className="border-y border-zinc-200 bg-zinc-50"><Container><div className="grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Workflow" title="A clearer flow, end to end." /><ol className="mt-8 space-y-4">{study.workflow.map((step, index) => <li key={step} className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-zinc-950 text-xs font-semibold text-white">{index + 1}</span><p className="pt-1 text-sm leading-6 text-zinc-700">{step}</p></li>)}</ol></div><div><SectionHeading eyebrow="Intended outcomes" title="What this product direction is designed to improve." /><p className="mt-6 text-sm leading-6 text-zinc-600">As a concept product, these are intended outcomes, not claims of measured client results.</p><CheckList items={study.outcomes} className="mt-6" /></div></div></Container></Section>
    <section className="bg-blue-600 py-14 text-white"><Container className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-blue-100">Have a similar challenge?</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Let&apos;s shape the right system for it.</h2></div><ButtonLink href="/contact" variant="secondary">Start a Project <ArrowRight className="size-4" /></ButtonLink></Container></section>
  </>;
}
