import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import type { ContentItem } from "@/lib/content";
import { ArchitectureDiagram } from "@/components/content-cards";
import { ButtonLink, CheckList, Container, Eyebrow, Section, SectionHeading } from "@/components/ui";

export function DetailPage({ item, kind }: { item: ContentItem; kind: "service" | "industry" | "solution" }) {
  const Icon = item.icon;
  const subject = kind === "industry" ? "organization" : kind === "solution" ? "system" : "product";
  return <>
    <section className="border-b border-zinc-200 bg-zinc-50 py-16 sm:py-22"><Container><Link href={`/${kind === "service" ? "services" : `${kind}s`}`} className="text-sm font-medium text-zinc-500 hover:text-blue-600">{kind === "service" ? "Services" : `${kind[0].toUpperCase()}${kind.slice(1)}s`} <span aria-hidden="true">/</span></Link><div className="mt-8 grid gap-10 lg:grid-cols-[1.2fr_0.8fr] lg:items-end"><div><Eyebrow>{item.eyebrow}</Eyebrow><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-tight text-zinc-950 sm:text-6xl">{item.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">{item.description}</p><ButtonLink href={item.slug === "technology-consulting" ? "/consultation" : "/contact"} className="mt-8">{item.slug === "technology-consulting" ? "Book a Free Consultation" : "Discuss Your Project"}</ButtonLink></div><div className="relative min-h-48 overflow-hidden rounded-lg bg-zinc-950 p-6 text-white"><div className="absolute inset-0 grid-bg opacity-30" /><div className="relative"><span className="grid size-12 place-items-center rounded-md bg-white/10 text-blue-300"><Icon className="size-6" /></span><p className="mt-10 max-w-xs text-lg font-medium leading-7">A practical route from the problem to a {subject} your team can rely on.</p></div></div></div></Container></section>
    <Section><Container><div className="grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="The challenge" title="Where this work helps." /><CheckList items={item.problems} className="mt-8" /></div><div className="rounded-lg border border-zinc-200 bg-zinc-50 p-7 sm:p-9"><p className="text-sm font-medium text-zinc-500">Our focus</p><p className="mt-4 text-2xl font-semibold tracking-tight text-zinc-950">{item.short}</p><p className="mt-5 text-sm leading-6 text-zinc-600">We work through the business context, user needs, constraints, and operations together so the solution earns its place.</p></div></div></Container></Section>
    {item.slug === "technology-consulting" && <Section className="border-y border-zinc-200 bg-zinc-950 text-white"><Container><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><Eyebrow className="text-blue-300">You do not need a stack picked out</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-tight">&quot;I have a problem.&quot; is enough to begin.</h2></div><div><p className="text-lg leading-8 text-zinc-300">Tell Ventrio what is getting in the way. We analyze the context and recommend a product strategy, architecture, technology stack, integrations, AI opportunities, security and scalability considerations, delivery roadmap, and estimated effort.</p><ButtonLink href="/consultation" variant="secondary" className="mt-7">Book a Free Consultation</ButtonLink></div></div></Container></Section>}
    <Section className="border-y border-zinc-200 bg-zinc-50"><Container><SectionHeading eyebrow="Capabilities" title="The work behind the outcome." /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{item.capabilities.map((capability, index) => <div className="flex items-center gap-3 rounded-md border border-zinc-200 bg-white p-4" key={capability}><span className="grid size-7 place-items-center rounded-full bg-blue-50 text-xs font-semibold text-blue-700">{String(index + 1).padStart(2, "0")}</span><span className="text-sm font-medium text-zinc-800">{capability}</span></div>)}</div></Container></Section>
    {item.slug === "ai" && <Section><Container><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><Eyebrow>Applied AI architecture</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">AI that knows when to answer, act, and escalate.</h2><p className="mt-5 text-base leading-7 text-zinc-600">The most useful AI systems are connected to approved information, explicit workflows, and human judgment. We design the full operating loop, not just a chat interface.</p></div><div className="relative overflow-hidden rounded-lg border border-zinc-200 bg-zinc-950 p-5 text-white sm:p-8"><div className="absolute inset-0 grid-bg opacity-20" /><div className="relative grid gap-3 sm:grid-cols-3"><AICell label="Approved knowledge" tone="blue" /><AICell label="Retrieval & context" tone="violet" /><AICell label="AI assistant" tone="blue" /><AICell label="Business workflows" tone="neutral" /><AICell label="Human review" tone="neutral" /><AICell label="Feedback & evaluation" tone="violet" /></div></div></div></Container></Section>}
    <Section><Container><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><Eyebrow>Built to last</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">A deliberate foundation, not a one-off delivery.</h2><p className="mt-5 text-base leading-7 text-zinc-600">Ventrio brings product thinking, engineering discipline, and practical operations into the same conversation from the beginning.</p><div className="mt-7 space-y-4">{item.outcomes.map((outcome) => <div className="flex gap-3 text-sm text-zinc-700" key={outcome}><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-blue-600" />{outcome}</div>)}</div></div><ArchitectureDiagram items={["Discovery and design", "Secure, scalable engineering", "Operations, insight, and iteration"]} /></div></Container></Section>
    <section className="bg-blue-600 py-14 text-white"><Container className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-blue-100">Ready to explore the right approach?</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Let&apos;s map the next practical step.</h2></div><ButtonLink href="/contact" variant="secondary">Start a Project <ArrowRight className="size-4" /></ButtonLink></Container></section>
  </>;
}

function AICell({ label, tone }: { label: string; tone: "blue" | "violet" | "neutral" }) {
  const styles = { blue: "border-blue-400/40 bg-blue-500/15", violet: "border-violet-400/40 bg-violet-500/15", neutral: "border-white/15 bg-white/[0.06]" };
  return <div className={`rounded-md border p-4 ${styles[tone]}`}><span className="block h-1.5 w-8 rounded-full bg-white/65" /><p className="mt-5 text-xs font-medium text-white">{label}</p></div>;
}
