import Link from "next/link";
import { ArrowRight, Braces, Cloud, Gauge, Lightbulb, LockKeyhole, Network, Sparkles } from "lucide-react";
import { ContentCard, ProductJourney } from "@/components/content-cards";
import { LeadForm } from "@/components/lead-form";
import { PortfolioGrid } from "@/components/portfolio-grid";
import { Badge, ButtonLink, Container, Eyebrow, Section, SectionHeading } from "@/components/ui";
import { services } from "@/lib/content";
import { pageMetadata } from "@/lib/site";

export const metadata = pageMetadata("Ventrio", "Technology consulting and product development for ambitious organizations. We turn ideas and business problems into powerful digital products.", "/");

const focusServices = ["technology-consulting", "product-development", "ai", "web-development", "cloud", "data-analytics", "cybersecurity", "legacy-modernization"];
const buildOptions = [
  ["SaaS Platforms", "/solutions/saas", Cloud], ["ERP Systems", "/solutions/erp", Network], ["CRM Platforms", "/solutions/crm", Braces], ["University Management Systems", "/solutions/university-os", Lightbulb], ["Mobile Applications", "/services/mobile-development", Gauge], ["Customer Portals", "/services/web-development", LockKeyhole], ["AI Assistants", "/services/ai", Sparkles], ["Business Automation", "/solutions/business-automation", ArrowRight], ["Analytics Dashboards", "/services/data-analytics", Gauge], ["E-commerce Platforms", "/services/web-development", Network], ["Internal Enterprise Tools", "/services/software-development", Braces], ["APIs & Integrations", "/services/software-development", ArrowRight],
] as const;

export default function Home() {
  const visibleServices = focusServices.map((slug) => services.find((service) => service.slug === slug)).filter(Boolean);
  return <>
    <section className="relative overflow-hidden bg-zinc-950 pb-20 pt-20 text-white sm:pb-24 sm:pt-28 lg:pb-32 lg:pt-36"><div className="absolute inset-0 grid-bg opacity-35" /><div className="absolute left-1/2 top-0 h-[500px] w-[900px] -translate-x-1/2 bg-[radial-gradient(ellipse_at_center,rgba(37,99,235,0.3),transparent_63%)]" /><Container className="relative"><div className="mx-auto max-w-4xl text-center"><Eyebrow className="text-blue-300">Technology Consulting <span aria-hidden="true">&#8226;</span> Product Development <span aria-hidden="true">&#8226;</span> AI</Eyebrow><h1 className="mt-6 text-5xl font-semibold tracking-tight sm:text-7xl lg:text-8xl">Your Vision.<br /><span className="text-blue-400">Our Technology.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-300 sm:text-lg">We turn ideas, business challenges, and software requirements into powerful digital products that are built to scale.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><ButtonLink href="/contact">Start Your Project</ButtonLink><ButtonLink href="/work" variant="secondary">Explore Our Work</ButtonLink></div></div><ProductJourney /></Container></section>
    <section className="border-b border-zinc-200 bg-white py-7"><Container className="flex flex-col gap-3 text-center sm:flex-row sm:items-center sm:justify-between sm:text-left"><p className="text-sm font-medium text-zinc-900">Built for ambitious teams, startups, and organizations.</p><p className="text-sm text-zinc-500">Strategy, design, engineering, AI, and ongoing technology care.</p></Container></section>
    <Section><Container><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="What we do" title="Technology that moves the business forward." description="Bring us an opportunity, a hard-to-fix workflow, a legacy system, or an early idea. We will help you decide what to build and build it with you." /><ButtonLink href="/services" variant="text">All services</ButtonLink></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visibleServices.map((service) => service && <ContentCard item={service} basePath="/services" key={service.slug} />)}</div></Container></Section>
    <Section className="border-y border-zinc-200 bg-zinc-50"><Container><SectionHeading eyebrow="What can we build?" title="Products made for real operations." description="Focused digital systems for the work, customers, and decisions that define an organization." /><div className="mt-10 grid divide-x-0 divide-y divide-zinc-200 border-y border-zinc-200 md:grid-cols-2 md:divide-x md:divide-y-0 lg:grid-cols-3">{buildOptions.map(([title, href, Icon]) => <Link href={href} key={title} className="group flex items-center gap-4 p-5 transition-colors hover:bg-white"><span className="grid size-9 place-items-center rounded-md bg-white text-zinc-700 shadow-sm ring-1 ring-zinc-200"><Icon className="size-4" /></span><span className="flex-1 text-sm font-semibold text-zinc-900">{title}</span><ArrowRight className="size-4 text-zinc-400 transition-transform group-hover:translate-x-1 group-hover:text-blue-600" /></Link>)}</div></Container></Section>
    <Section><Container><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><SectionHeading eyebrow="Selected concepts" title="Show the system, not just the screen." description="Our concept products make complex services feel clear and operational. They are demonstrations of what a focused product approach can unlock, not claims about client work." /><div className="lg:text-right"><Badge tone="neutral">Concept products and demo projects</Badge><p className="mt-3 text-sm leading-6 text-zinc-600">University OS, Business ERP, AI Customer Support, and Restaurant Management.</p></div></div><div className="mt-10"><PortfolioGrid /></div></Container></Section>
    <Section className="bg-zinc-950 text-white"><Container><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><Eyebrow className="text-blue-300">Have an idea?</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Let&apos;s turn it into technology.</h2><p className="mt-5 max-w-md text-base leading-7 text-zinc-300">You do not need a technical plan before we talk. Tell us what you want to achieve, and we will help you find a clear path forward.</p><Link href="/consultation" className="mt-7 inline-flex text-sm font-semibold text-blue-300 hover:text-blue-200">Prefer a consultation? Book a free conversation <ArrowRight className="ml-2 size-4" /></Link></div><LeadForm source="IDEA" /></div></Container></Section>
  </>;
}
